apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-configmap
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
      "UserAppCon": "Server=192.168.105.21,1433;Database=ecommerce;User Id=sa;Password=Anhyeuem2002a@;TrustServerCertificate=true;"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "Jwt": {
        "Secret": "{{ .Values.jwtSecret }}"
      },
      "AllowedHosts": "*"  
    }