services:
  nginx:
    # Note : Only nginx:alpine supports bcrypt.
    # If you don't need to use bcrypt, you can use a different tag.
    # Ref. https://github.com/nginxinc/docker-nginx/issues/29
    image: "nginx:alpine"
    ports:
      - 443:443
    depends_on:
      - registry
    volumes:
      - /Users/noroom113/IdeaProjects/final-project-b20dccn678_thuanpt/lima/immutable/resource/registry/auth:/etc/nginx/conf.d
      - /Users/noroom113/IdeaProjects/final-project-b20dccn678_thuanpt/lima/immutable/resource/registry/auth/nginx.conf:/etc/nginx/nginx.conf:ro

  registry:
    image: registry:2
    volumes:
      - ./data:/var/lib/registry