apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ecommerce
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5ub3Jvb20xMTMuY29tIjp7InVzZXJuYW1lIjoibm9yb29tMTEzIiwicGFzc3dvcmQiOiJBbmh5ZXVlbTIwMDJhQCIsImF1dGgiOiJibTl5YjI5dE1URXpPa0Z1YUhsbGRXVnRNakF3TW1GQSJ9fX0=
